[config]
schemaVersion = "0.0.1"

[package]
namespace = "Anthony.Stai"
name = "FamilyFriendly"
description = "A non serious mod which kills you if you swear."
websiteUrl = "https://github.com/ItzRock/FamilyFriendly"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Notest-VoiceRecognitionAPI = "1.2.1"

[build]
icon = "./ts-assets/icon.png"
readme = "README.md"
outdir = "./dist"

[[build.copy]]
source = "./LICENSE"
target = "/"

[[build.copy]]
source = "./ts-assets/naughtywords.txt"
target = "/"

[[build.copy]]
source = "./FamilyFriendly/bin/Release/netstandard2.1/AnthonyStai.FamilyFriendly.dll"
target = "/BepInEx/plugins/FamilyFriendly/"

[publish]
communities = ["content-warning"]
repository = "https://thunderstore.io"
[publish.categories]
content-warning = ["bepinex", "mods", "client-side"]